[tool.poetry]
name = "simulateur_trafic_package"
version = "0.1.0"
description = "Internal package metadata for simulateur_trafic"
package-mode = false

[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"